name: 'Rusty '
favicon: null
layout_spectrum: 0.6597451025154442
typography_spectrum: 0.5320157192181796
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/21489e42-037a-4859-9d48-eec0d00f90dc.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Rusty '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7bd38'
    - '#1a1a18'
    - '#e7e9fa'
    - '#b2b8b4'
    - '#5b5c57'
  brandStrength: 0.21246153069660068
  lightness: 0.6211118772625923
  saturation: 0.6538732077460736
  rhythmicContrast: 0.440291146049276
purpose: []
