name: 'Rusty '
favicon: null
layout_spectrum: 0.07418
typography_spectrum: 0.56839
title: 'Rusty '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9bf21'
    - '#10100f'
    - '#e8ecfc'
    - '#b0b3b0'
    - '#5d5e59'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
