title: 'Rusty '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.0625
  rhythmicContrast: 0
  brandColors:
    - '#f9bf21'
    - '#10100f'
    - '#e8ecfc'
    - '#b0b3b0'
    - '#5d5e59'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Rusty '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.56839
layout_spectrum: 0.7795699
